name: PouchScanner Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, simplexml

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Set up Node.js
        with:
            node-version: '20'
            check-latest: true
            using: 'node20'
            main: 'main.js'

      - name: Install Node dependencies
        run: npm install

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release


